name: Compile iBootpatch2 ipad6
on: [push]
jobs:
  linux-build:
    strategy:
      matrix:
        arch:
          - runner: ubuntu-22.04
            name: x86_64
          - runner: ubuntu-22.04-arm
            name: aarch64

    name: linux-${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}

    steps:
      - uses: actions/checkout@v7

      - name: Run make
        run: make

      - name: Zip iBootpatch2
        run: zip -r iBootpatch2-ipad6_linux-${{ matrix.arch.name }}.zip iBootpatch2

      - name: Update latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload latest \
            iBootpatch2-ipad6_linux-${{ matrix.arch.name }}.zip \
            --clobber -R ${{ github.repository }}

          gh release edit latest \
            --title "Latest" \
            --target ${{ github.sha }} -R ${{ github.repository }}
